### ISSUE TITLE
Problem with cross compiling server 4.7.3

### ISSUE THREAD

**Issue by Tokariew** [TomenetGame/tomenet#12]
I have problems with latest security hardening 81707db5db155e96e868ccd282dea6ea98b580f3 when cross compiling on fedora. 
I get binary but it doesn't work either in wine or native in windows. It don't give any error when I try to run it :/

**Comment by mhirki** [comment]
Yeah, looks like -pie just breaks everything. I disabled it with commit 3a924c31f1722c9b9f5fff2834dfb33251979064.
