### ISSUE TITLE
Stable master

### ISSUE THREAD

**Issue by jezek** [TomenetGame/tomenet#2]
Hello, this isn't much of an issue, it's more of an discussion about some enhancements/ideas.

It is a good practice, that the ```master``` branch is the latest stable release, possibly the same version that is running as server at ```europe.tomenet.eu``` and is advertised as latest client in [download section of TomeNET page](https://tomenet.eu/downloads.php).

The idea is that the development is done in other branches (or in your fork) and is merged (pull request is filled) to ```master``` only when its is complete (possibly tested) and you are pretty confident that he code can be build and used as official server/client without troubles (this is meant only for code changes, documentation can be merged without issues). 

Or tagging would be helpful, to mark the releases and latest stable.

This helps in community development in the future (less confusion) or if some build and deploy automation is needed.

I'm writing this on behalf of about 100 commits to ```master``` in past 5 days. I mean, it is very good, the development progresses with this pace (and kudos for the work), but a little bit organization will do only good.

Maybe some outline for guidelines for versioning & branching will be good.
What are your thoughts about versioning, branching, release tagging and build automation?

**Comment by mhirki** [comment]
I don't currently see a need for a separate development branch. The master branch is relatively stable. People are supposed to test their changes locally before pushing or creating a pull request. The official server (europe.tomenet.eu) is updated quite frequently from the master branch.

I am going to tag at least the previous release so that people have some way of finding it through git.

**Comment by jezek** [comment]
Thanks for your prompt answer.

That's what I failed to communicate. I couldn't find out where one version stops and another begins. Tags did the work. Perfect. Issue solved.
