### ISSUE TITLE
Antistatic wrapping check

### ISSUE THREAD

**Issue by EpicOrange** [TomenetGame/tomenet#23]
https://github.com/TomenetGame/tomenet/blob/6ab6a848b719a8d3f1c38bb57575296194ed02f1/src/server/cmd6.c#L3617-L3618

This should be `!= SV_SI_MDEVP_WRAPPING`, I think (to match the below)

https://github.com/TomenetGame/tomenet/blob/6ab6a848b719a8d3f1c38bb57575296194ed02f1/src/server/cmd6.c#L4506-L4507

**Comment by CBlueGH** [comment]
Thanks, fixed.
