### ISSUE TITLE
Password change

### ISSUE THREAD

**Issue by Tokariew** [TomenetGame/tomenet#24]
Currently it is possible to use Account Settings to change password and leave it blank. When logging out in that situation server will respond with: `"You must enter a password too!"` But it is no longer possible.

We should prevent that situation…

**Comment by CBlueGH** [comment]
Fixed. PASSWORD_MIN_LEN 6 now enforces minimum length for new passwords. Existing accounts are not affected so they can still log on even if their password is (hopefully not -_-) shorter.
