### ISSUE TITLE
Resampling issues on Linux

### ISSUE THREAD

**Issue by Tokariew** [TomenetGame/tomenet#36]
There are some weird resampling issue for me, when the music is in 44100 Hz sample rate and the effect is in 48000 Hz. The audio occasionally glitches for me. Changing samplerate to 48000 in .tomenetrc fix the issue for me, but not sure if other sound effect will not be glitched.

Tested on official 4.8.0 linux build, with ALSA and pipewire sound server.

For me glitched was audible with boomerang effect with Kurzel YS music pack in Training Tower

**Comment by CBlueGH** [comment]
Hmmm. Audio is handled by SDL 2.
Which sound effects were 48kHz though? I should probably just resample those to 44.1kHz.

**Comment by Tokariew** [comment]
All the track from sound which don't have 44.1kHz
```
'./weather/snow/snow.ogg',
 './player/misc/death/dspldeth.wav',
 './weather/rain/rain.ogg',
 './player/misc/death/dspdiehi.wav',
 './player/commands/bash/door/break/smash.ogg',
 './player/alert/warning/warning.ogg',
 './player/alert/error/bell.ogg',
 './misc/shatter_potion/glass1.ogg',
 './magic/blink/blink.ogg',
 './magic/teleport/teleport.ogg',
 './item/weapon/magestaff.ogg',
 './item/gold/coinscut.ogg',
 './item/gold/coins.ogg',
 './combat/parry_weapon/parry_metal.ogg',
 './combat/fire/boomerang.ogg',
 './ambient/timed/seagull/seagulls.ogg',
 './ambient/timed/owl/owl.ogg',
 './ambient/timed/birdofprey/birdofprey2.ogg',
 './ambient/timed/birdofprey/birdofprey4.ogg',
 './ambient/timed/owl/owl2.ogg',
 './ambient/timed/birdofprey/birdofprey3.ogg',
 './ambient/timed/birdofprey/birdofprey.ogg',
 './player/commands/open/chest/open2.ogg'
```
And all the samplig rate which are in the unpacked sound pack
```
Sampling rate                            : 11.025 kHz
Sampling rate                            : 22.05 kHz
Sampling rate                            : 44.1 kHz
Sampling rate                            : 48.0 kHz
```

**Comment by CBlueGH** [comment]
Thanks, sound pack updated (the stand-alone download, also used by the updater, not the sound fx that are inside existing client-downloads).
