### ISSUE TITLE
Support to CMake

### ISSUE THREAD

**Issue by Andres6936** [TomenetGame/tomenet#4]
Do you plan to support CMake for the build of the project?

**Comment by jezek** [comment]
What is the advantage of using cmake instead of make? Is it worth the work?

**Comment by Andres6936** [comment]
Modern development environments (CLion, Eclipse and Visual Studio) work with `CMake` files to parse the program source code, allowing warnings to be generated and warning of dangerous code as redundancies in the program.

`CMake` is just a wrapper around `Make` (also from Ninja), so CMake abstracts from the complications of Makefiles.

**What's it all about:** If the project has growth expectations (I suppose it has), one way to start is to allow **_working with the code in modern workspaces_**, that is, using IDE.

**_Is this really necessary?_** yes, CLion (my current IDE) for example: it only works with projects that contain a CMakeLists.txt (Makefiles support in CLion is being developed), and potentially the non-use of `CMake` leaves out potential contributors.

**Comment by jezek** [comment]
Thanks for your explanation. I'm not in charge of tis project, only a curious fan of rpg games and programming arts. I'm not familiar with ```cmake``` nor written a MakeFile by myself.

I think, that if ```CMake``` is necessary for your IDE, then you should definitely try to implement support for it (or find one, who does) and make a Pull request. I'm sure, that if you don't break any old build functionality, the admins will accept the PR.

Have a nice time and lot of fun with this project.

**Comment by Andres6936** [comment]
Thank you very much for your answer @jezek 

You are right, `CMake` does not break any build process and can perfectly coexist with Makefiles.
