### ISSUE TITLE
Problems Compiling under Ubuntu64

### ISSUE THREAD

**Issue by Andres6936** [TomenetGame/tomenet#5]
**Command:** 

```sh
cd src && make
```

**Error:**

```sh
gcc -O2 -g -pipe -Wall -DUSE_X11 -DUSE_GCU -I/usr/X11R6/include -D_XOPEN_SOURCE -D_BSD_SOURCE -DMEXP=19937 -std=c99 -DSOUND_SDL `sdl-config --cflags` -D_DEFAULT_SOURCE -DACC32 -fPIC -Wno-format-truncation  -Iserver -Iserver/lua -o client/snd-sdl.o -c client/snd-sdl.c
client/snd-sdl.c:51:10: fatal error: SDL_mixer.h: No such file or directory
   51 | #include "SDL_mixer.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
makefile:472: recipe for target 'client/snd-sdl.o' failed
make: *** [client/snd-sdl.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Suggestions:**

Use:

The problems originate from the fact that the headers of SDL and SDL2 are usually found in `/usr/local/include/SDL` or `/usr/include/SDL`.

```cxx
#include "SDL/SDL_mixer.h"
```

**Comment by Andres6936** [comment]
_I have compiled the program by doing the following:_

I modified the Makefile to remove the `-DSOUND_SDL` definition and the link to `-lSDL_mixer`

**Comment by jezek** [comment]
Have you tried to install, sdl mixer developer package?

For me on Ubuntu 19.10 worked:
```bash
$ sudo apt install libsdl1.2-dev libsdl-mixer1.2-dev  
```

**Comment by Andres6936** [comment]
_@jezek thanks very much. Your suggestion worked correctly._

**Comment by jezek** [comment]
@Andres6936 The suggestion above is the bare minimum for compile (I think). Maybe you want to install some more packages for full sound support. Please read the ```Linux (compiling from source):``` section in [Installation & setup docs](https://www.tomenet.eu/guide.php?chapter=2).
