### ISSUE TITLE
TomeNET 4.9.n on Arch GNU/Linux seems to run the command-line instead of graphical client

### ISSUE THREAD

**Issue by dchmelik** [TomenetGame/tomenet#52]
A friend of mine tried TomeNet 4.9.0, 4.9.1 but when he had problems, screenshot he sent me seems to be what I was told is the command-line client more for server usage:  He also gets font error messages which I'll try to get later.

![tomenet](https://github.com/TomenetGame/tomenet/assets/10347890/65d10d08-c33e-4cde-a40b-051b5146a4e3)

**Comment by mhirki** [comment]
The command-line interface is the fallback option when X11 interface isn't working for some reason. I guess this can be confusing for new people.

**Comment by dchmelik** [comment]
Thanks; he fixed it with the previous font problem fixed.
