### ISSUE TITLE
Graphics: strong freezes when there a lot of graphic tiles on the screen

### ISSUE THREAD

**Issue by EvgenijK** [TomenetGame/tomenet#59]
# Description

There are some strong freezing on client side if many graphical tiles are on the screen.

You can see it on the attached video.

On the video terrain(sand) has graphic tile.
I also have smaller freezes with objects.(i mapped almost all objects from k_info)

I'm using this tileset (`terrain` branch):  https://github.com/EvgenijK/TomeNET-Tileset/tree/terrain

I hope @jezek can look at this.

https://github.com/TomenetGame/tomenet/assets/8179946/595021e7-e61f-4d95-8d90-6735e705657e

**Comment by EvgenijK** [comment]
Maybe look into Angband or Mangband source code?   
IIRC they use SDL for graphics

**Comment by mhirki** [comment]
Are you running the Windows or the Linux client? I tried your tileset with the Windows client but it seems to hang forever. Very Sleepy profiler shows it's stuck calling NtGdiGetPixel and NtGdiSetPixel inside recreateGraphicsObjects. Looks like it's stuck in an infinite loop there.

I'll try with the Linux client next.

**Comment by mhirki** [comment]
I go the tileset working with the Linux client. I can confirm I'm seeing small freezes when running around inside the Training Tower. CPU usage looks a bit high for the Xorg process. Running "perf top" shows wfbPixmapToRegion from libwfb.so at the top eating a lot of CPU cycles.

**Comment by mhirki** [comment]
Apparently the Windows client starts much faster when running it under Wine on Linux. So the graphical tile rescaling is just extremely slow on native Windows. The faster alternative on Windows would be to call GdipBitmapLockBits and GdipBitmapUnlockBits functions.

**Comment by mhirki** [comment]
Commit b5a96afdb7c328b1b45683504bb0b968cc685e2e adds a cache for composed graphical tiles which speeds up drawing significantly. I also decided to simply call StretchBlt() to resize the tiles in the Windows client because it is much faster (commit aadce1a8eb9b8bbb90793e7a7e1d7e9aacacc2f0).

**Comment by EvgenijK** [comment]
@mhirki saw your commits, awesome work, i'm very happy to see that graphics is fast now)
