### ISSUE TITLE
TomeNET server SDL make error 

### ISSUE THREAD

**Issue by dchmelik** [TomenetGame/tomenet#63]
On Slackware GNU/Linux 15 (64-bit, up-to-date) I had a TomeNET server SDL make error: [gist](http://gist.github.com/dchmelik/19055855a36a958c57d15673c5428b57).  Is it a different SDL version?  I have the following

- SDL2-2.0.20-x86_64-1
- SDL2_gfx-1.0.4-x86_64-3
- SDL2_image-2.0.5-x86_64-3
- SDL2_mixer-2.0.4-x86_64-5
- SDL2_net-2.0.1-x86_64-4
- SDL2_sound-2.0.2-x86_64-1_SBo (from [SlackBuilds.org](http://slackbuilds.org), an unofficial but endorsed build script site)
- SDL2_ttf-2.0.18-x86_64-1

**Comment by mhirki** [comment]
If you're only intested in running the server, you don't need to compile the client at all. You can only compile the server and accedit by running `make tomenet.server accedit`.

You can also get rid of SDL sound support by commenting out -DSOUND_SDL from makefile.

If you do want to compile the client with sound support, you need to a newer version of SDL_mixer. Mix_GetMusicPosition() was introduced in version 2.6.1 of SDL_mixer.

**Comment by dchmelik** [comment]
thanks
