### ISSUE TITLE
fatal errors compiling server slash commands

### ISSUE THREAD

**Issue by dchmelik** [TomenetGame/tomenet#64]
On Slackware GNU/Linux 15 (64-bit, up-to-date) with GCC 11.2.0, I had 'too many fatal errors' compiling server slash commands: [gist](http://gist.github.com/dchmelik/e21f70b240099e0a5f8c9b7f16323e28).

**Comment by mhirki** [comment]
You're compiling with Clang so GCC version doesn't matter. I guess you can try switching to GCC to see if your Clang is somehow broken. Did you modify server/slash.c somehow?

**Comment by dchmelik** [comment]
I see.  I didn't modify slash.c.  About all I changed was Bree (add shops), some character generation, configuration/'defines' and renaming 'draconian' 'dragon-kin'.  I can make my changes available on IRC and later here.

**Comment by mhirki** [comment]
This should by fixed by commit b7185743fb216f9ba2d5167060fa9fdaa46d7525. Apparently you were compiling with `FUN_SERVER` enabled.

**Comment by dchmelik** [comment]
yes: fixed
